# Generated by Django 5.2.6 on 2025-09-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimdocument_claimstatushistory_alter_claim_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='insurance_id',
            field=models.CharField(default='N/A', help_text='Insurance ID or policy number', max_length=50),
        ),
    ]
